### ISSUE TITLE
PHP Fatal error:  Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by guangrei** [clue/reactphp-shell#17]
hi, install library just like instruction in readme.md and got  `"clue/shell-react": "^0.2"` in my composer.json but when run any samples code this error is throwing
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Clue\React\Shell\ProcessLauncher::__construct(), 0 passed in /home/guangrei/myphp/test.php on line 8 and exactly 1 expected in /home/guangrei/myphp/vendor/clue/shell-react/src/ProcessLauncher.php:14
Stack trace:
#0 /home/guangrei/myphp/test.php(8): Clue\React\Shell\ProcessLauncher->__construct()
#1 {main}
  thrown in /home/guangrei/myphp/vendor/clue/shell-react/src/ProcessLauncher.php on line 14

```
my php version is 7.4.

**Comment by guangrei** [comment]
code in test.php
```php
<?php

use Clue\React\Shell\ProcessLauncher;

require 'vendor/autoload.php';


$launcher = new Clue\React\Shell\ProcessLauncher();

$shell = $launcher->createDeferredShell('bash');

$shell->execute('echo -n $USER')->then(function ($result) {
    var_dump('current user', $result);
});

$shell->execute('env | sort | head -n10')->then(function ($env) {
    var_dump('env', $env);
});

$shell->end();
```

**Comment by clue** [comment]
@guangrei Thanks for reporting!

It looks like you're using the documentation/examples from the current `master` version while running the `v0.2.0` release. Your above code should work against the current `master` version and the upcoming `v0.3.0` release version (#16) :+1:

(https://github.com/clue/reactphp-sqlite/issues/40)

**Comment by t-lock** [comment]
@clue I ran into the same issue. Might be worth going back to https://github.com/clue/reactphp-shell/blob/4121d5ca2f60322830d547c7fe3c0fcbc65068df/examples/php.php until v0.3.0 release. 

For me, I'd prefer to use the new syntax, so I uninstalled current release and installed the `dev-master` version, but I suppose you wouldn't want to make that the default install instructions in readme.

**Comment by SimonFrings** [comment]
> For me, I'd prefer to use the new syntax, so I uninstalled current release and installed the dev-master version, but I suppose you wouldn't want to make that the default install instructions in readme.

@t-lock Agree with you. I think it makes sense to do what benefits you the most.

I don't know when `v0.3.0` will go live, we're currently involved in a lot of other tasks that need our attention. If you need things to speed up in here, consider supporting the project and we'll take a look ;)
